cache:
  paths:
    - node_modules/

lint:
  image: node:13
  script:
    # Set up variable for commit range for unified-diff support.
    - export TRAVIS_COMMIT_RANGE="$(git merge-base HEAD master)...$(git rev-parse HEAD)"
    - yarn install --frozen-lockfile
    # We fetch the branches, since suggestions are limited to files changed relative to the master branch.
    - git fetch origin master
    # Lint the gulpfile with eslint.
    - ./node_modules/.bin/eslint gulpfile.js
    # This runs a gulp job which runs remark lint checks, both suggestions and errors.
    - ./node_modules/.bin/gulp ci | tee output.log
    - bash -c '! egrep -q "(problem\W)" output.log'
  only:
    - external_pull_requests

lint-master:
  image: node:13
  script:
    - yarn install --frozen-lockfile
    # This runs a gulp job which runs remark lint checks, only errors.
    - ./node_modules/.bin/gulp problems | tee output.log
    - bash -c '! egrep -q "(problem\W)" output.log'
  only:
    - master

# This does a test build, which checks for broken internal links.
test-build:
  image: python:3
  script:
    - pip install -r requirements.txt mkdocs
    - mkdocs build --strict
  only:
    - external_pull_requests
    - master