# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: remark
        name: remark
        language: system
        entry: sh -c 'cd .config/remark/ && yarn && yarn run remark-changed'
        always_run: true
        pass_filenames: false
        verbose: true
      - id: mkdocs
        name: mkdocs
        language: script
        entry: ./.config/mkdocs/mkdocs.sh
        always_run: true
        pass_filenames: false
        verbose: true
  - repo: https://github.com/executablebooks/mdformat
    # Keep this in sync with the version in .config/mkdocs/pyproject.toml
    rev: 1.0.0
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-mkdocs
          - mdformat-black
          - mdformat-config
          - mdformat-footnote
          - mdformat-frontmatter
          - mdformat-simple-breaks
          - mdformat-tables
          - mdformat-web
          - mdformat-wikilink

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: fix-byte-order-marker
      - id: check-yaml
        args: ["--unsafe"]
      - id: check-json
      - id: check-added-large-files
  - repo: https://github.com/mattlqx/pre-commit-search-and-replace
    rev: v1.1.9
    hooks:
      - id: search-and-replace
        language_version: default
        types: [markdown]
        args:
          - "--config=.config/pre-commit-search-and-replace.yaml"
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        types: [markdown]
        args:
          - "--ignore-words=.config/codespell-ignore"
          - "--write-changes"
ci:
  # We skip checks that have their own actions or external dependencies.
  skip: [remark, codespell, mkdocs]
