# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: remark
        name: remark
        language: docker_image
        entry: civicactions/guidebook-lint:latest remark.sh
        always_run: true
        pass_filenames: false
  - repo: local
    hooks:
      - id: mkdocs
        name: mkdocs
        language: script
        entry: ./.config/mkdocs/mkdocs.sh
        always_run: true
        pass_filenames: false
  - repo: local
    hooks:
      - id: link-check
        name: link-check
        language: docker_image
        entry: --entrypoint node civicactions/guidebook-lint:latest /usr/src/node_modules/.bin/markdown-link-check -q -c .config/markdown.links.config.json --
        types: [markdown]
        always_run: true
        pass_filenames: true
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: fix-byte-order-marker
      - id: check-yaml
        args: ["--unsafe"]
      - id: check-json
      - id: check-added-large-files
  - repo: https://github.com/mattlqx/pre-commit-search-and-replace
    rev: v1.0.5
    hooks:
      - id: search-and-replace
        types: [markdown]
        args:
          - "--config=.config/pre-commit-search-and-replace.yaml"
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
      - id: codespell
        types: [markdown]
        args:
          - "--ignore-words=.config/codespell-ignore"
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.9-for-vscode
    hooks:
      - id: prettier
ci:
  # We skip checks that have their own actions or external dependencies.
  skip: [remark, codespell, mkdocs, link-check]
