# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      # Install poetry
      # https://python-poetry.org/docs/#installing-manually
      - pip install poetry
    post_install:
      # Configure git authentication
      - git config --global credential.helper store
      - echo "https://${GH_TOKEN}:@github.com" > $HOME/.git-credentials
      # VIRTUAL_ENV needs to be set manually for now.
      # See https://github.com/readthedocs/readthedocs.org/pull/11152/
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry -C .config/mkdocs/ install
    pre_build:
      # Symlink all files to a .docs directory so we can build outside the root
      - ln -sfT . .docs

mkdocs:
  configuration: .config/mkdocs.yml
