name: "Run remark-lint with reviewdog"
description: "🐶 Run remark-lint with reviewdog on pull requests for documentation projects."
author: "civicactions"
inputs:
  github_token:
    description: "GITHUB_TOKEN."
    required: true
    default: ${{ github.token }}
runs:
  using: "docker"
  # We need to keep the action at the top level so we can build the same as Docker Hub.
  image: "lint/Dockerfile"
  args:
    - remark.sh