site_name: CivicActions Guidebook - Beta
repo_url: https://github.com/CivicActions/handbook/
site_url: https://handbook.civicactions.com/en/latest/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.expand
  favicon: img/favicon.ico
  logo: img/ca-logo-white.svg
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - toc:
      title: On this page
plugins:
  - search
extra_css:
  - css/extra.css
extra_javascript:
  #- js/extra.js
  # Read the Docs requires JQuery for its JavaScript code to inject the flyout
  # menu. Material for MkDocs does not come with JQuery.
  - "https://code.jquery.com/jquery-3.6.2.min.js"
nav:
  - Welcome: index.md
  - About CivicActions: 
    - Mission and values: about-civicactions/mission-values.md
    - Culture: about-civicactions/culture.md
