site_name: CivicActions Guidebook - Beta
repo_url: https://github.com/CivicActions/handbook/
site_url: https://handbook.civicactions.com/en/latest/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.expand
  favicon: img/favicon.ico
  logo: img/CA-Short-Logo-White.svg
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - toc:
      title: On this page
plugins:
  - search
extra_css:
  - css/extra.css
#nav:
#- Welcome: index.md
