site_name: CivicActions Guidebook - Beta
repo_url: https://github.com/CivicActions/handbook/
site_url: https://handbook.civicactions.com/en/latest/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.expand
  favicon: img/favicon.ico
  logo: img/ca-logo-white.svg
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - toc:
      title: On this page
plugins:
  - search
extra_css:
  - css/extra.css
extra_javascript:
  #- js/extra.js
  # Read the Docs requires JQuery for its JavaScript code to inject the flyout
  # menu. Material for MkDocs does not come with JQuery.
  - "https://code.jquery.com/jquery-3.6.2.min.js"
nav:
  - Welcome: index.md
  - About CivicActions:
    - Mission and values: about-civicactions/mission-values.md
    - Culture: about-civicactions/culture.md
    - Diversity, Equity, Inclusion, and Accessibility (DEIA) at CivicActions: purpose.md
      - Defining diversity, equity, inclusion, and accessibility (DEIA): defining-dei.md
      - Affinity channels: affinity-channels.md
      - DEIA: Get involved: deia-get-involved.md
      - DEIA resources: resources.md
    - Our structure:
      - Organization':' department, projects, practice areas, and pods: how-we-are-organized.md
      - Organizational structure: org-structure.md
      - Management team: management-team.md
    - Background and history: background-and-history.md
    - Our annual summit: our-annual-summit.md
  - Employee Benefits:
      - Benefits policy (US employees): us-benefits-policy.md
      - Compensation (US employees): us-compensation.md
      - Technology stipend policy (US employees): us-tech-stipend.md
      - Benefits policy (Canadian employees): canada-benefits-policy.md
      - Technology stipend (Canadian employees): canada-tech-stipend.md
      - Professional development: professional-development.md
      - Employee referral bonus program: employe-referral-bonus.md
      - On-call stipends: on-call-stipend.md
   
  
