site_name: CivicActions Guidebook - Beta
repo_url: https://github.com/CivicActions/handbook/
site_url: https://handbook.civicactions.com/en/latest/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.expand
  favicon: img/favicon.ico
markdown_extensions:
  - toc:
      title: On this page
plugins:
  - search
extra_css:
  - css/extra.css
