name: "Run repo specific lint tools"
description: "Runs remark and related lint tools on pull requests for documentation projects."
author: "civicactions"
inputs:
  github_token:
    description: "GITHUB_TOKEN."
    required: true
    default: ${{ github.token }}
  command:
    description: "Command to run"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.command }}
