name: "Run remark-lint with reviewdog for documentation projects"
description: "🐶 Run remark-lint with reviewdog on pull requests for documentation projects."
author: "civicactions"
inputs:
  workdir:
    description: "Working directory relative to the root directory."
    required: false
    default: "."
  remark_paths:
    description: "Remark-lint paths to check."
    required: false
    default: "."
  remark_args:
    description: "Additional remark-lint input arguments."
    required: false
    default: ""
  # Reviewdog related inputs
  github_token:
    description: "GITHUB_TOKEN."
    required: true
    default: ${{ github.token }}
  tool_name:
    description: "Tool name to use for reviewdog reporter."
    required: false
    default: "remark-lint"
  reporter:
    description: "Reporter of reviewdog command [github-pr-check, github-pr-review, github-check]."
    required: false
    default: "github-pr-check"
  filter_mode:
    description: "Filtering mode for the reviewdog command [added, diff_context, file, nofilter]."
    required: false
    default: "added"
  reviewdog_flags:
    description: "Additional reviewdog flags."
    required: false
    default: ""
runs:
  using: "docker"
  image: "Dockerfile"

# Ref: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: "zoom-in"
  color: "purple"
