# Navigation of the entire site is managed here, both the main menu items and their child pages.
nav:
  - Home: README.md
  - About us:
      - about-civicactions/README.md
      - Background: about-civicactions/README.md
      - about-civicactions/mission-values.md
      - about-civicactions/culture.md
      - Diversity, Equity, Inclusion, and Accessibility (DEIA):
          - about-civicactions/diversity-equity-inclusion/purpose.md
          - about-civicactions/diversity-equity-inclusion/defining-dei.md
          - about-civicactions/diversity-equity-inclusion/affinity-channels.md
          - about-civicactions/diversity-equity-inclusion/deia-get-involved.md
          - about-civicactions/diversity-equity-inclusion/resources.md
      - Our structure:
          - about-civicactions/our-structurehow-we-are-organized.md
          - about-civicactions/our-structureorg-structure.md
          - about-civicactions/our-structuremanagement-ops.md
      - about-civicactions/annual-summit.md
  - Employee benefits:
      - employee-benefits/README.md
      - employee-benefits/us-compensation.md
      - employee-benefits/us-tech-stipend.md
      - employee-benefits/canada-benefits-policy.md
      - employee-benefits/canada-tech-stipend.md
      - employee-benefits/professional-development.md
      - employee-benefits/employee-referral-bonus.md
      - employee-benefits/on-call-stipend.md
  - Company policies:
      - company-policies/employment/us/README.md
      - company-policies/expenses.md
      - company-policies/travel-time-tracking-and-expenses.md
      - company-policies/timesheets.md
      - company-policies/security.md
      - Employment policies (US employees):
          - Employment: company-policies/README.md
          - company-policies/employment/us/README.md
          - company-policies/employment/us/introductory-period.md
          - company-policies/anti-harassment-policies.md
          - company-policies/covid19-safety.md
      - company-policies/code-of-conduct.md
      - company-policies/employment/workplace-guidelines.md
      - company-policies/annual-review-process.md
      - company-policies/performance-management.md
      - company-policies/employment/leaving-civicactions.md
      - company-policies/health-safety-security.md
      - New hire orientation:
          - company-policies/new-hire-orientation/welcome.md
          - company-policies/new-hire-orientation/buddy-program.md
          - company-policies/new-hire-orientation/elevator-pitch.md
          - company-policies/new-hire-orientation/intro-open-source.md
          - company-policies/new-hire-orientation/meetings-and-meeting-tools.md
          - company-policies/new-hire-orientation/people-planning.md
          - company-policies/new-hire-orientation/security-training.md
          - company-policies/new-hire-orientation/training-resources.md
          - company-policies/new-hire-orientation/video-call-best-practices.md
          - company-policies/new-hire-orientation/virtual-workplace-basics.md
  - Our practices and tools:
      - common-practices-tools/README.md
      - Agile:
          - common-practices-tools/agile/agile-overview.md
          - common-practices-tools/agile/agile-practices.md
          - common-practices-tools/agile/backlog-refinement.md
          - common-practices-tools/agile/daily-scrum-calls.md
          - common-practices-tools/agile/tickets-cards.md
          - common-practices-tools/agile/sprint-cycle.md
          - common-practices-tools/agile/sprint-demo.md
          - common-practices-tools/agile/sprint-planning-meetings.md
          - common-practices-tools/agile/sprint-retrospectives.md
      - common-practices-tools/balance-scores.md
      - common-practices-tools/best-practices-for-managers-and-team-members.md
      - CivicActions style guide: "https://civicactions-style-guide.readthedocs.io/en/latest/introduction/brand-overview/"
      - common-practices-tools/gold-star-program.md
      - Security awareness and tools:
          - common-practices-tools/security/awareness.md
          - Setting up and using Yubikey:
              - common-practices-tools/security/yubikey/README.md
              - common-practices-tools/security/yubikey/linux.md
              - common-practices-tools/security/yubikey/macosx.md
          - common-practices-tools/security/drupal-rmf-support.md
          - common-practices-tools/security/encryption.md
          - common-practices-tools/security/gnupg.md
          - Incidents:
              - common-practices-tools/security/contingency-plan.md
              - common-practices-tools/security/incident-response-checklist.md
              - common-practices-tools/security/incident-response-plan.md
              - common-practices-tools/security/incidents.md
      - common-practices-tools/skills-base.md
      - Software and support:
          - common-practices-tools/software-and-support/support.md
          - company-policies/new-hire-orientation/bookmarks.md
          - common-practices-tools/software-and-support/email.md
          - common-practices-tools/software-and-support/github.md
          - common-practices-tools/software-and-support/google-calendar.md
          - common-practices-tools/software-and-support/google-docs.md
          - common-practices-tools/software-and-support/google-meet.md
          - common-practices-tools/software-and-support/jira.md
          - common-practices-tools/software-and-support/markdown.md
          - common-practices-tools/software-and-support/slack.md
          - common-practices-tools/software-and-support/trello.md
          - common-practices-tools/software-and-support/zoom.md
      - common-practices-tools/telephone.md
  - Practice areas:
      - practice-areas/README.md
      - Accessibility:
          - practice-areas/accessibility/accessibility-practice-area.md
          - practice-areas/accessibility/accessibility-how-to.md
      - Design and research:
          - practice-areas/design-and-research/README.md
          - practice-areas/design-and-research/audiences-and-outcomes-guide.md
          - practice-areas/design-and-research/content-audit-guide.md
          - practice-areas/design-and-research/stakeholder-interviews-guide.md
          - practice-areas/design-and-research/story-mapping-guide.md
          - practice-areas/design-and-research/usability-testing-guide.md
          - practice-areas/design-and-research/user-personas-guide.md
      - Engineering:
          - practice-areas/engineering/engineering-calls.md
          - practice-areas/engineering/accessibility.md
          - practice-areas/engineering/drupal-practice-area.md
          - practice-areas/engineering/most-important-decision-in-developing-a-drupal-site-contributed-vs-custom-development.md
          - practice-areas/engineering/drupal-developer-tips-for-getting-the-most-out-of-open-source.md
          - practice-areas/engineering/git.md
          - practice-areas/engineering/security-compliance.md
          - Tech Lead:
              - practice-areas/engineering/tech-lead/README.md
          - practice-areas/engineering/text-editors-ides.md
      - Project management:
          - practice-areas/project-management/project-management-checklists.md
          - practice-areas/project-management/growth-mindset.md
          - practice-areas/project-management/contract-expiration-tracking.md
          - practice-areas/project-management/mods-and-extensions.md
          - practice-areas/project-management/contractual-requirements.md
          - practice-areas/project-management/project-folder.md
          - practice-areas/project-management/general-tooling-guidelines-for-project-teams.md
          - practice-areas/project-management/hard-conversations.md
          - practice-areas/project-management/innovation.md
          - practice-areas/project-management/invoicing.md
          - practice-areas/project-management/leave-requests-and-stepping-away.md
          - practice-areas/project-management/listserv-setup.md
          - practice-areas/project-management/project-offboarding.md
          - practice-areas/project-management/onboarding-new-project-team-member.md
          - practice-areas/project-management/planning-onsite-meetings.md
          - practice-areas/project-management/project-calendar.md
          - practice-areas/project-management/pm-role.md
          - practice-areas/project-management/starting-new-project.md
          - practice-areas/project-management/team-working-agreements-instructions.md
          - practice-areas/project-management/templates.md
          - practice-areas/project-management/pm-training.md
          - practice-areas/project-management/pm-unanet-tasks.md
      - Project support:
          - practice-areas/help-desk/helpdesk.md
          - practice-areas/help-desk/help-desk-agile.md
          - practice-areas/help-desk/working-practices.md
          - practice-areas/help-desk/project-support-checklist.md
  - About this guidebook:
      - about-this-guidebook/README.md
      - about-this-guidebook/why-guidebook-is-open.md
      - about-this-guidebook/editing-the-guidebook.md
      - about-this-guidebook/reviewing-pull-requests.md
      - about-this-guidebook/automatic-checking.md
      - about-this-guidebook/guidebook-governance.md
      - about-this-guidebook/writing-style-guide.md
      - about-this-guidebook/markdown-for-guidebook.md
      - LICENSE.md

# Mkdocs and Material theme configuration
site_name: CivicActions Guidebook
repo_url: https://github.com/CivicActions/guidebook/
site_url: https://guidebook.civicactions.com/en/latest/
docs_dir: "../.docs"
edit_uri: edit/master/
theme:
  name: material
  custom_dir: theme_overrides
  language: custom
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.footer
    - navigation.path
    - content.action.edit
  favicon: assets/images/favicon.ico
  logo: assets/images/ca-logo-white.svg
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - toc:
      title: On this page
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html
plugins:
  - search
  - git-revision-date-localized
extra_css:
  - assets/css/extra.css
extra_javascript:
  #- js/extra.js
  # Read the Docs requires JQuery for its JavaScript code to inject the flyout
  # menu. Material for MkDocs does not come with JQuery.
  - "https://code.jquery.com/jquery-3.6.2.min.js"
extra:
  analytics:
    provider: google
    property: G-8Z4Z4B9GFL
