name: Checking for common typos

on:
  pull_request:

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: codespell-project/actions-codespell@master
        with:
          path: docs
          ignore_words_file: .config/codespell-ignore
