name: Checking all markdown and links site-wide

on:
  # Automatic check weekly
  schedule:
    - cron: "0 9 * * 1"
  # Manually triggered using GitHub's UI
  workflow_dispatch:

jobs:
  check-links:
    name: runner / linkspector
    # Once https://github.com/UmbrellaDocs/action-linkspector/issues/32 is resolved, we can use ubuntu-latest
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Run linkspector on all links
        uses: umbrelladocs/action-linkspector@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          fail_on_error: true
          config_file: .config/linkspector.yml
          filter_mode: nofilter
      - name: Run remark-lint on all files
        uses: ./.config/remark/
        with:
          command: remark-all.sh
      - name: Send GitHub Action trigger data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v2.0.0
        if: failure()
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
