name: Check All Markdown links

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 9 * * 1"

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: ".config/markdown.links.config.json"
