name: Check for any potential redirects that may be missing.

on:
  pull_request:

jobs:
  missing-redirect-check:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check if there are any file deletions and additions relative to master and no redirect.yml changes
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          DELETION_COUNT=$(git diff --summary origin/${{ github.event.pull_request.base.ref }}..${{ github.event.pull_request.head.ref }} | grep -E '^\s*delete' | wc -l)
          CREATION_COUNT=$(git diff --summary origin/${{ github.event.pull_request.base.ref }}..${{ github.event.pull_request.head.ref }} | grep -E '^\s*create' | wc -l)
          RENAME_COUNT=$(git diff --summary origin/${{ github.event.pull_request.base.ref }}..${{ github.event.pull_request.head.ref }} | grep -E '^\s*rename' | wc -l)
          REDIRECTS_CHANGED=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }}..${{ github.event.pull_request.head.ref }} | grep -q '^\.config/redirects\.yml$'; echo $?)
          if { [ $DELETION_COUNT -gt 0 ] && [ $CREATION_COUNT -gt 0 ] || [ $RENAME_COUNT -gt 0 ]; } && [ $REDIRECTS_CHANGED -eq 1 ]; then
            echo "CONDITIONS_MET=true" >> $GITHUB_ENV
          fi

      - name: Add PR comment
        if: env.CONDITIONS_MET == 'true'
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            **Potentially missing redirects**
            There appear to be renamed (or added and removed) files in this pull request, but [redirect.yml](.config/redirect.yml) was not edited. This could result in broken links.
            If pages were moved or removed (and sensible alternatives exist), please edit [redirect.yml](.config/redirect.yml) to add redirects for these.
            If not, feel free to ignore this message.
