name: Checking site build

on:
  pull_request:

jobs:
  mkdocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: snok/install-poetry@v1
        with:
          version: 1.3.2
      - name: Run mkdocs to check build.
        run: ./config/mkdocs/mkdocs.sh
