name: mkdocs

on:
  push:
  pull_request:

jobs:
  mkdocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: Run mkdocs to check build.
        uses: ./lint
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          command: mkdocs.sh
