name: mkdocs

on:
  pull_request:

jobs:
  mkdocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run mkdocs
        uses: docker://civicactions/handbook-lint:latest
        with:
          entrypoint: /bin/bash
          args: mkdocs.sh
