name: pre-commit

on:
  pull_request:

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: mkdir -p output/
      - run: pre-commit run -a codespell | tail -n +4 > output/codespell.txt
      - name: comment PR
        uses: machine-learning-apps/pr-comment@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: output/codespell.txt
  pre-commit:
    runs-on: ubuntu-latest
    needs: codespell
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0
        with:
          token: ${{ secrets.PRE_COMMIT_TOKEN }}
